version: '3.8'
services:
    cripto-app:
        image: cripto-app:latest
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        environment:
            NODE_ENV: production
