version: '3.8'
services:
    cripto-app:
        image: cripto-app:v1
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '4000:4000'
        environment:
            NODE_ENV: production
