"""revision migration

Revision ID: 07d2e620255e
Revises: 
Create Date: 2024-07-18 15:22:28.819065

"""
from typing import Sequence, Union
import fastapi_users_db_sqlalchemy

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07d2e620255e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=30), nullable=True),
    sa.Column('lastname', sa.String(length=30), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('sold', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_admin_id'), 'admin', ['id'], unique=False)
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.String(length=36), nullable=False),
    sa.Column('sold', sa.Integer(), nullable=True),
    sa.Column('nr_ref', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_id'), 'card', ['id'], unique=False)
    op.create_table('demo_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.String(length=36), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('order_type', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demo_order_id'), 'demo_order', ['id'], unique=False)
    op.add_column('referal', sa.Column('id_parent', sa.String(length=36), nullable=False))
    op.add_column('referal', sa.Column('id_child', sa.String(length=36), nullable=False))
    op.create_foreign_key(None, 'referal', 'user', ['id_parent'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'referal', 'user', ['id_child'], ['id'], ondelete='CASCADE')
    op.add_column('wallet', sa.Column('id_user', sa.String(length=36), nullable=False))
    op.create_foreign_key(None, 'wallet', 'user', ['id_user'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet', type_='foreignkey')
    op.drop_column('wallet', 'id_user')
    op.drop_constraint(None, 'referal', type_='foreignkey')
    op.drop_constraint(None, 'referal', type_='foreignkey')
    op.drop_column('referal', 'id_child')
    op.drop_column('referal', 'id_parent')
    op.drop_index(op.f('ix_demo_order_id'), table_name='demo_order')
    op.drop_table('demo_order')
    op.drop_index(op.f('ix_card_id'), table_name='card')
    op.drop_table('card')
    op.drop_index(op.f('ix_admin_id'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
