"""remove field

Revision ID: b21fe97e3004
Revises: 2c23820297af
Create Date: 2024-07-17 13:45:32.725308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b21fe97e3004'
down_revision: Union[str, None] = '2c23820297af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('status', mysql.VARCHAR(length=30), nullable=True))
    # ### end Alembic commands ###
