version: '3.8'
services:
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: begu
            MYSQL_DATABASE: mydb
            MYSQL_USER: sandu
            MYSQL_PASSWORD: begu
        ports:
            - '3306:3306'
        volumes:
            - db_data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        ports:
            - '8080:80'

volumes:
    db_data:
